### ISSUE TITLE
Black screen on PS5 with Unity 2022.3.x.

### ISSUE THREAD

**Issue by RicardoAmplify** [AmplifyCreations/FXAA#2]
Black screen on PS5 with Unity 2022.3.x. Requires further testing on device.

**Comment by diogovtx** [comment]
Fixed in [62b6b25dd9c34cc92c9c37b0e990949f6e3a1e7e](https://github.com/AmplifyCreations/FXAA/commit/62b6b25dd9c34cc92c9c37b0e990949f6e3a1e7e).
Waiting for fix confirmation from user.

**Comment by diogovtx** [comment]
Confirmed fixed.
